apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  labels:
    k8s-app: kube-Devops
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      k8s-app: kube-Devops
  template:
    metadata:
      labels:
        k8s-app: kube-Devops
    spec:
      containers:
        - name: test-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
